# creating symbolic links to import files as module

all: ./ga_data/helper_functions.py ./ga_data/stats_helper.py

./ga_data/helper_functions.py: 
	ln -s ../py/helper_functions.py $@

./ga_data/stats_helper.py: 
	ln -s ../py/stats_helper.py $@
